---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - apt: update_cache=yes

- hosts: application
  handlers:
  roles:
    - base
    - nginx